### ISSUE TITLE
breaking bad in viewing activity breaks with unicode bugs

### ISSUE THREAD

**Issue by pellcorp** [andrewleech/plugin.video.netflixbmc#16]
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.UnicodeDecodeError'>
Error Contents: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/jason/.kodi/addons/plugin.video.netflixbmc/default.py", line 1101, in <module>
    listViewingActivity(type)
  File "/home/jason/.kodi/addons/plugin.video.netflixbmc/default.py", line 472, in listViewingActivity
    title = htmlParser.unescape(matchTitle1[0]).replace("</span>", "")
  File "/usr/lib/python2.7/HTMLParser.py", line 475, in unescape
    return re.sub(r"&(#?[xX]?(?:[0-9a-fA-F]+|\w{1,8}));", replaceEntities, s)
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
-->End of Python script error report<--

**Comment by pellcorp** [comment]
I am about to submit a PR to fix.

**Comment by pellcorp** [comment]
Sorry, I had not updated to your latest master, bug seems to have already been fixed.
